In [2]:
import numpy as np
lst=[1,2,3,4,5,6,7,8]
arr=np.array(lst)
print(arr)

[1 2 3 4 5 6 7 8]


In [3]:
matrix_lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_lst)
print("Matrix:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [9]:
arr1=np.arange(1,11)
print("", arr1)
arr2=np.arange(1,11,2)
print("", arr2)

 [ 1  2  3  4  5  6  7  8  9 10]
 [1 3 5 7 9]


In [13]:
zero_arr=np.zeros(3)
print("", zero_arr)

 [0. 0. 0.]


In [ ]:
ones_matrix = np.ones((10, 10))
print("10x10 Ones:\n", ones_matrix)

10x10 Ones:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
lin_arr = np.linspace(1, 11, 25)
print("Linspace 25 numbers from 1 to 11:\n", lin_arr)

Linspace 25 numbers from 1 to 11:
 [ 1.          1.41666667  1.83333333  2.25        2.66666667  3.08333333
  3.5         3.91666667  4.33333333  4.75        5.16666667  5.58333333
  6.          6.41666667  6.83333333  7.25        7.66666667  8.08333333
  8.5         8.91666667  9.33333333  9.75       10.16666667 10.58333333
 11.        ]


In [4]:
identity = np.eye(10)
print("10x10 Identity Matrix:\n", identity)

10x10 Identity Matrix:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
rand_uniform = np.random.rand(5)
print("Random Uniform [0,1]:", rand_uniform)

Random Uniform [0,1]: [0.31959504 0.80595862 0.98146363 0.57340295 0.05762653]


In [10]:
randn_1d = np.random.randn(8)
print("Randn 1D:", randn_1d)

Randn 1D: [-0.03433395  0.34822577 -1.10393612  0.39566424  0.57649773 -0.81341174
  1.1126427   0.25891888]


In [15]:
randn_2d = np.random.randn(6, 6)
print("Randn 6x6:\n", randn_2d)

Randn 6x6:
 [[ 0.34163293 -0.22518846 -0.9843834  -0.06688115  1.95543956 -0.01951639]
 [ 0.00879418  0.56967068 -1.28561944  0.64153177 -0.76151047 -0.26839553]
 [-0.05577748 -2.12113276 -0.82213942 -0.80406457 -1.72912862  0.66692281]
 [-0.83220724  0.53802669 -0.23550546 -1.01121741 -1.40139204 -0.52883341]
 [ 0.94268138 -0.64417403  0.69324472  0.09644292 -0.52107152  0.77866538]
 [-0.70670823 -0.36737498  1.77183622 -0.19618103 -0.34165131  1.41921785]]


In [17]:
rand_int = np.random.randint(1, 6, 10)
print("Random int between 1-5:", rand_int)

Random int between 1-5: [1 3 3 1 4 5 5 5 3 4]


In [18]:
seq_arr = np.arange(25)
print("Sequential array:", seq_arr)

Sequential array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of a:", a.shape)

Shape of a: (2, 3)


In [20]:
a_flat = np.array([1, 2, 3, 4, 5, 6])
reshaped = a_flat.reshape((2, 3))
print("Reshaped to 2x3:\n", reshaped)

Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]


In [21]:
arr_min = np.array([10, 3, 7, 22, 5])
print("Minimum Value:", np.min(arr_min))

Minimum Value: 3


In [ ]:
r = np.array([10, 20, 50, 5])
print("Index of max value:", np.argmax(r))

Index of max value: 3


In [5]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[:5]=1000
print("", a)

 [1000 1000 1000 1000 1000    6    7    8    9   10]


In [8]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("", mat)

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
c=np.arange(1,10)
print("addition is ",c+c)
print("subtraction is ",c-c)
print("multiplication is",c*c)

addition is  [ 2  4  6  8 10 12 14 16 18]
subtraction is  [0 0 0 0 0 0 0 0 0]
multiplication is [ 1  4  9 16 25 36 49 64 81]


In [9]:
a=np.array([1,2,3,4,5,])
b=np.array([6,7,8,9,10])
print("", a+b)

 [ 7  9 11 13 15]


In [10]:
angles = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [11]:
exp=np.array(np.arange(1,10))
pow=3
print(exp**pow)

[  1   8  27  64 125 216 343 512 729]


In [12]:
sqrt_arr = np.array([4, 9, 16])
print("Square Roots:", np.sqrt(sqrt_arr))

Square Roots: [2. 3. 4.]


In [13]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Element-wise Matrix Multiplication:\n", mat * mat)

Element-wise Matrix Multiplication:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
